### ISSUE TITLE
Got this issue on run the sample

### ISSUE THREAD

**Issue by MADRamesh** [Azure-Samples/SpeechToText-WebSockets-Javascript#33] opened 2017-09-25 10:19 UTC
![image](https://user-images.githubusercontent.com/18552160/30803848-cc56a7d8-a208-11e7-815c-4e31659a6711.png)

I got trail key for bing speech api it works fine in text to speech but not here.
It was worked previously.
please do needful on this.

**Comment by zhouwangzw** [comment] 2017-09-25 10:26
Have you tried your free trial key with Speech-to-text REST API? For example. using cURL as described [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstarted-curl).

**Comment by MADRamesh** [comment] 2017-09-25 10:29
@zhouwangzw:
i tried with javascript websocket API.

**Comment by zhouwangzw** [comment] 2017-09-25 11:13
403 Error usually means the user request does not match what service expects. It could be due to an invalid subscription key/authroization token, or the audio format/code is not supported, and etc. Did you try Javascript Websocket API with [our sample](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstartedjswebsockets) or with your own application?

**Comment by MADRamesh** [comment] 2017-09-25 11:17
@zhouwangzw:
I tried with your sample only. The same key works fine Text-To-Speech (https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/Samples-Http/CSharp) sample.

Also that previously the websocket sample was worked perfectly. Now only am facing this issue.

**Comment by raaaar** [comment] 2017-09-25 11:29
I'm also experiencing the same issue. Looks like the problem is on the server-side. Will update this thread as soon as there's any progress on this issue.

**Comment by MADRamesh** [comment] 2017-09-25 11:34
@raaaar:
thanks for your update. please update on this ASAP.

**Comment by ancilt26** [comment] 2017-09-25 11:38
I've got the same issue where it was working fine at the start when i provided the subscription key. After a few tries I got the same error response as MADRamesh 
I'm also certain I haven't exceeded the API limits

**Comment by raaaar** [comment] 2017-09-26 08:33
Looks like things work again. Closing this issue for now, feel free to reopen if you observe any anomalies.

**Closed by raaaar** 2017-09-26 08:33 UTC
